kernel:
    resource: ../src/Kernel.php
    type: annotation

##
# Authorization
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"

##
# Admin
##
admin:
    resource: ../src/Controller/Admin
    type: annotation
    prefix: 'admin'
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
    prefix: 'admin'
admin_mailer:
    resource: "@PdMailerBundle/Resources/config/routing.yaml"
    prefix: 'admin'

##
# Web
##
homepage:
    resource: ../src/Controller/Web
    type: annotation
