##
# Authorization
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"
    prefix: 'auth'

##
# Admin
##
admin:
    resource: ../src/Controller/
    type: annotation
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
    prefix: 'admin'
admin_mailer:
    resource: "@PdMailerBundle/Resources/config/routing.yaml"
    prefix: 'admin'

##
# Homepage
##
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: homepage.html.twig
