kernel:
    resource: ../src/Kernel.php
    type: annotation

##
# Authorization
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"

##
# Admin
##
admin:
    resource: ../src/Controller/Admin
    type: annotation
    prefix: 'admin'
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
    prefix: 'admin'
redirect_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: security_login
        permanent: true

##
# API
##
api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: api
