imports:
    - { resource: "defaults.yaml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Migrations/'
            - '../src/Widgets/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Load Widgets
    App\Widgets\:
        resource: '../src/Widgets/*'
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }

    # Load DB Configurator
    Pd\UserBundle\Configuration\ConfigInterface: '@App\Service\ConfigBag'
